# Generated by Django 5.2.4 on 2025-07-28 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPuntuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ponderacion', models.IntegerField(help_text='Porcentaje del total, ej: 40 para 40%')),
                ('puntaje_ideal_total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(help_text='ID del arete o RFID', max_length=50, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('peso_actual', models.FloatField(blank=True, null=True)),
                ('talla_actual', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('peso_ideal_min', models.FloatField(blank=True, null=True)),
                ('peso_ideal_max', models.FloatField(blank=True, null=True)),
                ('talla_ideal', models.FloatField(blank=True, null=True)),
                ('capa_colores', models.CharField(blank=True, help_text='Colores aceptados separados por comas', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('puntaje_ideal', models.IntegerField()),
                ('rango_aceptado_min', models.FloatField()),
                ('rango_aceptado_max', models.FloatField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='api.categoriapuntuacion')),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion_obtenida', models.FloatField()),
                ('fecha_calificacion', models.DateField(auto_now_add=True)),
                ('evaluador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('caracteristica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.caracteristica')),
                ('ejemplar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='api.ejemplar')),
            ],
            options={
                'unique_together': {('ejemplar', 'caracteristica', 'fecha_calificacion')},
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('FIEBRE', 'Fiebre Alta'), ('CELO', 'Posible Celo'), ('INACTIVIDAD', 'Inactividad Anormal')], max_length=20)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_read', models.BooleanField(default=False)),
                ('ejemplar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.ejemplar')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='ejemplar',
            name='raza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.raza'),
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('temperatura', models.FloatField(blank=True, null=True)),
                ('actividad', models.FloatField(blank=True, help_text='Nivel de actividad o pasos', null=True)),
                ('ejemplar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='api.ejemplar')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='Animal',
        ),
    ]
