# Generated by Django 5.2.4 on 2025-07-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_categoriapuntuacion_ejemplar_raza_caracteristica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejemplar',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='ejemplares_fotos/'),
        ),
    ]
