# Generated by Django 5.2.4 on 2025-07-29 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ejemplar_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejemplar',
            name='last_score_date',
            field=models.DateField(blank=True, help_text='Fecha de la última calificación', null=True),
        ),
        migrations.AddField(
            model_name='ejemplar',
            name='score_total',
            field=models.FloatField(blank=True, help_text='Último score total calculado para el ejemplar', null=True),
        ),
    ]
