# Generated by Django 5.2.4 on 2025-07-29 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ejemplar_last_score_date_ejemplar_score_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriapuntuacion',
            name='raza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias_puntuacion', to='api.raza'),
        ),
    ]
